controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\LoginForm;
use yii\web\Response;
use app\models\SignupForm;
use yii\web\UploadedFile;
use app\models\User;
use yii\base\InvalidArgumentException;
use yii\web\BadRequestHttpException;

class UserController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
           /* 'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],*/
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        $title = 'Вход';
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        $model->password = '';
        return $this->render('login', [
            'title' => $title,
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
      public function actionLogout()
      {
          Yii::$app->user->logout();

          return $this->goHome();
      }

    /**
     * Displays create page.
     *
     * @return string
     */
    public function actionSignup()
    {
        Yii::$app->name = 'Регистрация';
        $buttonName = 'Зарегистрироваться';

        $model = new SignupForm();

        if(isset($_POST['SignupForm'])){
            $model->attributes = $_POST['SignupForm'];
            $model->selectedAvatar = $_POST['SignupForm']['selectedAvatar'][0];
            if($model->signup()){
                Yii::$app->session->setFlash('success',
                    'Спасибо за регистрацию. На указанный email было отправлено письмо для её завершения.');
                return $this->goHome();
            }
        }

        $title = 'Регистрация';
        $registration = true;
        return $this->render('signup', [
            'title' => $title,
            'model' => $model,
            'buttonName' => $buttonName,
            'registration' => $registration,
        ]);
    }

    /**
     * Profile page.
     * @return Response|string
     */
    public function actionProfile()
    {
        Yii::$app->name = 'Профиль';
        $user = new User;
        $id = Yii::$app->user->identity->id;
        $model = $user->findIdentity($id);
        $title = 'Профиль';
        return $this->render('profile', [
            'title' => $title,
            'model' => $model,
        ]);
    }


    /**
     * Delete page.
     * @return string
     */
    public function actionDelete()
    {
        //$user = new User;
        $title = 'Удалить';
        $id = Yii::$app->user->identity->id;

        return $this->render('delete_user', [
            'title' => $title,
            'user_id' => $id,
        ]);
    }

    /**
    * Delete user action.
    * @return string
    */
    public function actionDelete_user()
    {
        $user = new User;
        $id = Yii::$app->user->identity->id;

        if($user->deleteUser($id)) {
            Yii::$app->session->setFlash('success', 'Ваш аккаунт удален.');
            return $this->goHome();
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'profile' page.
     * @return mixed
     */
    public function actionUpdate_information()
    {
        Yii::$app->name = 'Профиль';
        $title = 'Изменение профиля';
        $buttonName = 'Сохранить изменения';

        $user = new User;
        $id = Yii::$app->user->identity->id;
        $model = $user->findIdentity($id);


        if(isset($_POST['User'])) {

            $answer = $model->selectChange($_POST['User']);

            if($answer === 'success') {
                $model->updateUser($_POST['User'], $_FILES['User']['name']['avatar']);
                Yii::$app->session->setFlash('success', 'Изменение ваших данных прошло успешно.');

                return $this->redirect(['profile',
                'id' => $model->id,
                'model' => $model,
            ]);
            } else {
                $model = $answer;
            }
        }

        $registration = false;
        return $this->render('signup', [
            'title' => $title,
            'model' => $model,
            'buttonName' => $buttonName,
            'registration' => $registration,
        ]);
    }

    /**
     * Change password action.
     * If update is successful, the browser will be redirected to the 'profile' page.
     * @return string
     */
    public function actionUpdate_password() {

        $model = new User;
        $id = Yii::$app->user->identity->id;
        $model->scenario = User::SCENARIO_UPDATE_PASSWORD;
        if(isset($_POST['User'])) {
            $model->setAttributes($_POST['User']);
            if($model->validate()) {
                $newUser = $model->updatePassword($id);

                Yii::$app->session->setFlash('success', 'Изменение вашего пароля прошло успешно.');

                return $this->redirect(['profile',
                    'id' => $newUser->id,
                    'model' => $newUser,]);
            }
        }

        return $this->render('password', [
            'model' => $model,
        ]);
    }

    /**
     * Validate email
     *
     * @param string $token
     * @return mixed
     */
    public function actionVerificationEmail($token)
    {
        $user = User::findByEmailVerificationToken($token);

        if(is_null($user)) {
            Yii::$app->session->setFlash('error', 'Пользователь с таким email не существует. ' .
            'Попробуйте зарегистрироваться снова или обратитесь в службу поддержки сайта.');
            return $this->goHome();
        }

        if($user->status === User::STATUS_DELETED) {
            Yii::$app->session->setFlash('error', 'Пользователь с таким email был удален. ' .
                'Попробуйте зарегистрироваться снова под другим email или обратитесь в службу поддержки сайта.');
            return $this->goHome();
        } else if($user->status === User::STATUS_ACTIVE) {
            Yii::$app->session->setFlash('success', 'Ваш email уже подтвержден.');
            return $this->goHome();
        }

        if($user->isEmailVerificationTokenValid($token)) {
            $user->validateEmail();
            Yii::$app->session->setFlash('success', 'Вы подтвердили свой email и можете пользоваться данным сайтом.');
            return $this->goHome();
        } else {
            $title = 'Регистрация';
            Yii::$app->session->setFlash('error', 'Срок действия данной ссылки подтверждения email истек.');
            return $this->render('send_email', [
                'title' => $title,
                'user' => $user,
            ]);
        }
      }

    /**
     * Send email with verification_token again
     *
     * @param $id int
     * @return mixed
     */
      public function actionSendEmail($id) {

          $user = User::findById($id);
          if(SignupForm::sendEmail($user)) {
              Yii::$app->session->setFlash('success',
                  'Спасибо за регистрацию. На указанный email было отправлено письмо для её завершения.');
              return $this->goHome();
          }
          Yii::$app->session->setFlash('error',
              'Письмо не отправилось. Попробуйете еще раз.');
          return $this->goHome();

      }

    /**
     * If user forgot password, he can restore password
     * For it he should enter his email
     * @return mixed
     */
      public function actionRestorePassword() {

          $title = 'Восстановить';
          $this->layout = ('@app/views/layouts/main-login');
          $message = '';

          if (!Yii::$app->user->isGuest) {
              return $this->goHome();
          }

          $model = new User();
          $model->scenario = User::SCENARIO_RESTORE_PASSWORD;

          if(isset($_POST['User'])) {
              $user = User::findByEmail($_POST['User']['email']);
              if(is_null($user)) {
                  $message = 'Пользователя с таким email не существует.';
                  $model->email = $_POST['User']['email'];
              } else {
                  if($user->status === User::STATUS_DELETED) {
                      $message = 'Пользователь с таким email был удален.';
                      $model->email = $_POST['User']['email'];
                  } else if($user->status === User::STATUS_NOT_ACTIVE) {
                      $message = 'Данный email не подтвержден.';
                      $model->email = $_POST['User']['email'];
                  } else if($user->status === User::STATUS_ACTIVE) {
                      if(User::sendPasswordEmail($user)) {
                          return $this->render('send_token', [
                              'title' => $title,
                          ]);
                      }
                      $message = 'На указанный email уже было отправлено письмо со ссылкой для восстановления пароля.';
                  }
              }
          }

views/layouts/content.php
<?php
use yii\widgets\Breadcrumbs;
use dmstr\widgets\Alert;

?>
<div class="content-wrapper">
    <section class="content-header">
        <?php if (isset($this->blocks['content-header'])) { ?>
            <h1><?= $this->blocks['content-header'] ?></h1>
        <?php } else { ?>
            <h1>
                <?php
                if ($this->title !== null) {
                    echo \yii\helpers\Html::encode($this->title);
                } else {
                    echo \yii\helpers\Inflector::camel2words(
                        \yii\helpers\Inflector::id2camel($this->context->module->id)
                    );
                    echo ($this->context->module->id !== \Yii::$app->id) ? '<small>Module</small>' : '';
                } ?>
            </h1>
        <?php } ?>

        <?=
        Breadcrumbs::widget(
            [
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]
        ) ?>
    </section>

    <section class="content">
        <?= Alert::widget() ?>
        <?= $content ?>
    </section>
</div>

<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 2.0
    </div>
    <strong>Copyright &copy; 2019. Наша команда.</strong> All rights
    reserved.
</footer>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <!-- Home tab content -->
        <div class="tab-pane" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class='control-sidebar-menu'>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-user bg-yellow"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                            <p>New phone +1(800)555-1234</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                            <p>nora@example.com</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-file-code-o bg-green"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                            <p>Execution time 5 seconds</p>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class='control-sidebar-menu'>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="label label-danger pull-right">70%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Update Resume
                            <span class="label label-success pull-right">95%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-success" style="width: 95%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Laravel Integration
                            <span class="label label-waring pull-right">50%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Back End Framework
                            <span class="label label-primary pull-right">68%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

        </div>
        <!-- /.tab-pane -->

        <!-- Settings tab content -->
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked/>
                    </label>

                    <p>
                        Some information about this general settings option
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Allow mail redirect
                        <input type="checkbox" class="pull-right" checked/>
                    </label>

                    <p>
                        Other sets of options are available
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Expose author name in posts
                        <input type="checkbox" class="pull-right" checked/>
                    </label>

                    <p>
                        Allow the user to show his name in blog posts
                    </p>
                </div>
                <!-- /.form-group -->

                <h3 class="control-sidebar-heading">Chat Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Show me as online
                        <input type="checkbox" class="pull-right" checked/>
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Turn off notifications
                        <input type="checkbox" class="pull-right"/>
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Delete chat history
                        <a href="javascript::;" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                    </label>
                </div>
                <!-- /.form-group -->
            </form>
        </div>
        <!-- /.tab-pane -->
    </div>
</aside><!-- /.control-sidebar -->
<!-- Add the sidebar's background. This div must be placed
     immediately after the control sidebar -->
<div class='control-sidebar-bg'></div>

views/layouts/header.php
<?php
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */
?>

<header class="main-header">

    <?= Html::a('<span class="logo-mini"> Парсер </span><span class="logo-lg">' . Yii::$app->name . '</span>', Yii::$app->homeUrl, ['class' => 'logo']) ?>

    <nav class="navbar navbar-static-top" role="navigation">

        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">

            <ul class="nav navbar-nav">
                <li class="dropdown messages-menu">
                <a href="/applications/instruction" >
                    <span >Инструкция</span>
                </a>
                </li>
                <!-- User Account: style can be found in dropdown.less -->
                <?php if(!Yii::$app->user->isGuest):?>
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="<?= '/upload/user/' .
                            Yii::$app->user->identity->avatar ?>" class="img-circle user-image-small" alt="User Image"/>
                            <span class="hidden-xs"> <?= Yii::$app->user->identity->username ?></span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img src="<?= '/upload/user/' .
                                Yii::$app->user->identity->avatar ?>" class="img-circle" alt="User Image" id="user-image-big"/>
                                <p>
                                    <?= Yii::$app->user->identity->username ?>
                                    <small> На сайте с <?= Yii::$app->formatter->asDate(Yii::$app->user->identity->created_at, 'short') ?></small>
                                </p>
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <?= Html::a(
                                        'Профиль',
                                        ['/user/profile/' , 'id' => Yii::$app->user->identity->id],
                                        ['class' => 'btn btn-default btn-flat']
                                    ) ?>
                                </div>
                                <div class="pull-right">
                                    <?= Html::a(
                                        'Выйти',
                                        ['/user/logout'],
                                        ['data-method' => 'post', 'class' => 'btn btn-default btn-flat']
                                    ) ?>
                                </div>
                            </li>
                        </ul>
                    </li>
                <?php endif;?>
                <!-- User Account: style can be found in dropdown.less -->
            </ul>
        </div>
    </nav>
</header>

views/layouts/left.php
<aside class="main-sidebar">

    <section class="sidebar">

        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <?php if(!Yii::$app->user->isGuest):?>
                <img src="<?= '/upload/user/' .
                Yii::$app->user->identity->avatar ?>" class="img-circle" alt="User"/>
            </div>
            <div class="pull-left info">
                <p><?= Yii::$app->user->identity->username ?></p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
            <?php endif;?>
        </div>

        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
                <span class="input-group-btn">
                <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
            </div>
        </form>
        <!-- /.search form -->

        <?= dmstr\widgets\Menu::widget(
            [
                'options' => ['class' => 'sidebar-menu tree', 'data-widget'=> 'tree'],
                'items' => [
                    ['label' => 'МЕНЮ', 'options' => ['class' => 'header']],
                    ['label' => 'Новости', 'icon' => 'newspaper-o', 'url' => ['/news']],

                    !Yii::$app->user->isGuest ? (
                    ['label' => 'Параметры', 'icon' => 'file-code-o', 'url' => ['/settings'],
                        'items' => [
                            ['label' => 'Приложения', 'icon' => 'file-code-o', 'url' => ['/applications'],],
                            ['label' => 'Аккаунты', 'icon' => 'dashboard', 'url' => ['/accounts'],],
                            ['label' => 'Группы', 'icon' => 'file-code-o', 'url' => ['/groups'],],
                            ]
                        ]
                    ):(['label' => '']),
                    !Yii::$app->user->isGuest ? (
                    ['label' => 'Источники', 'icon' => 'dashboard', 'url' => ['/source']]
                    ):(['label' => '']),
                    !Yii::$app->user->isGuest ? (
                    ['label' => 'Публикации', 'icon' => 'dashboard', 'url' => ['/publish'],
                        'items' => [
                            ['label' => 'Ожидающие', 'icon' => 'file-code-o', 'url' => ['/publish'],],
                            ['label' => 'Архив', 'icon' => 'dashboard', 'url' => ['/archive'],],]
                    ]
                    ):(['label' => '']),
                    Yii::$app->user->can('EditRoles') ? (
                    ['label' => 'Роли', 'icon' => 'dashboard', 'url' => ['/admin']]
                    ):(['label' => '']),
                    Yii::$app->user->isGuest ? (
                    ['label' => 'Профиль', 'icon' => 'id-card-o', 'url' => ['/user/profile'], 'visible' => !Yii::$app->user->isGuest]
                    ):(
                    ['label' => 'Профиль', 'icon' => 'id-card-o', 'url' => ['/user/profile'],
                        'items' => [
                            Yii::$app->user->isGuest ?: (  ['label' => 'Обо мне', 'icon' => 'user',
                                'url' => ['/user/profile',], ]),
                            ['label' => 'Изменить данные', 'icon' => 'edit',
                                'url' => ['/user/update_information',], ],
                            ['label' => 'Изменить пароль', 'icon' => 'pencil',
                                'url' => ['/user/update_password', ], ],
                            ['label' => 'Удалить', 'icon' => 'remove',
                                'url' => ['/user/delete', ], ],
                        ],
                    ]
                    ),

                    Yii::$app->user->isGuest ? (
                    ['label' => 'Войти', 'icon' => 'sign-in', 'url' => ['/user/login']]
                    ) : (
                    ['label' => 'Выйти', 'icon' => 'sign-out', 'url' => ['/user/logout']]
                    ),

                ],
            ]
        ) ?>

    </section>

</aside>

views/layouts/main-login.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

dmstr\web\AdminLteAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="login-page">

<?php $this->beginBody() ?>

    <?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */


if (Yii::$app->controller->action->id === 'login') { 
/**
 * Do not use this code in your template. Remove it. 
 * Instead, use the code  $this->layout = '//main-login'; in your controller.
 */
    echo $this->render(
        'main-login',
        ['content' => $content]
    );
} else {

    if (class_exists('backend\assets\AppAsset')) {
        backend\assets\AppAsset::register($this);
    } else {
        app\assets\AppAsset::register($this);
    }

    dmstr\web\AdminLteAsset::register($this);

    $directoryAsset = Yii::$app->assetManager->getPublishedUrl('@vendor/almasaeed2010/adminlte/dist');
    ?>
    <?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body class="hold-transition skin-blue sidebar-mini">
    <?php $this->beginBody() ?>
    <div class="wrapper">

        <?= $this->render(
            'header.php',
            ['directoryAsset' => $directoryAsset]
        ) ?>

        <?= $this->render(
            'left.php',
            ['directoryAsset' => $directoryAsset]
        )
        ?>

        <?= $this->render(
            'content.php',
            ['content' => $content, 'directoryAsset' => $directoryAsset]
        ) ?>

    </div>

    <?php $this->endBody() ?>
    </body>
    </html>
    <?php $this->endPage() ?>
<?php } ?>

views/layouts/main_old.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>