controllers/AccountsController.php
<?php
/**
 * 23.09.2019
 * 21:37
 */

namespace app\controllers;

use app\models\tables\Groups;
use Codeception\Platform\Group;
use VK\Client\VKApiClient;
use app\models\tables\NetworkAccounts;
use app\models\VkAuth;
use yii\web\Controller;
use app\models\tables\Applications;

class AccountsController extends Controller
{

    public function actionIndex()
    {
        $userID = \Yii::$app->getUser()->getId();
        $app = new Applications();
        $acc = new NetworkAccounts();

        $userApplications = $app->findApplications($userID);
        $userAccounts = $acc->findAccounts($userID);

        $provider = $acc->getProvider($userID);

        return $this->render('index', [
            'provider' => $provider,
            'userApplications' => $userApplications,
            'userAccounts' => $userAccounts,
        ]);
    }
    public function actionGetCode()
    {
        $userID = \Yii::$app->getUser()->getId();
        $vkAuth = new VkAuth();

        $app = Applications::find()
            ->where(['user_id' => $userID, 'network_id' => $vkAuth->networkID])
            ->one();

        $this->redirect($vkAuth->linkForGetCode($app->app_id));
    }

    public function actionParseCode()
    {
        $codeFromUser = \Yii::$app->request->post()['code-input'];

        $validateWord = '/^https:\/\/oauth.vk.com\/blank.html#code=/';
        //проверяет, начинается ли $codeFromUser на https://oauth.vk.com/blank.html#code=

        if(strlen($codeFromUser)<= 37 || strlen($codeFromUser) >= 255) {
            echo $this->render('_modal', [
                'errorCodeFromUser' => 'length',
            ]);
        } else {
            if (preg_match($validateWord, $codeFromUser)) {

                $code = (new VkAuth())->parseCode($codeFromUser);
                $app = Applications::find()
                    ->where(['user_id' => \Yii::$app->getUser()->getId()])
                    ->one();
                $vkAuth = new VkAuth();
                $vkAuth->getAccessToken($code, $app);

            } else {
                echo $this->render('_modal', [
                    'errorCodeFromUser' => 'value',
                ]);
            }
        }
        /*$code = (new VkAuth())->parseCode($codeFromUser);
        $app = Applications::find()
            ->where(['user_id' => \Yii::$app->getUser()->getId()])
            ->one();

        $vkAuth = new VkAuth();
        $vkAuth->getAccessToken($code, $app);*/
    }

    public function actionDelete($id)
    {
        $userID = \Yii::$app->getUser()->getId();

        NetworkAccounts::deleteAll([
            'id' => $id,
            'user_id' => $userID,
        ]);

        Groups::deleteAll([
            'user_id' => $userID,
            'id_account' => $id
        ]);

        $this->redirect('/accounts');

    }

   /* public function actionVk()
    {

        $vk = new VKApiClient();
        $response = $vk->wall()->post('0dd83088b99ec2c9ab6f7998d08e6f60305b9043238905e2bf0a181228c29060bd3674f33fe1314346ce0', array(
            'message' => 'hi',
            //'owner_id' => '559492692',
            'owner_id' => '-186080195',
        ));

    }*/

}

views/accounts/_accTable.php
<?php
/**
 * 24.09.2019
 * 0:04
 */

use yii\grid\GridView;
use yii\helpers\Html;
use yii\grid\ActionColumn;

?>
<p>Account Table</p>

<div>
    <?= GridView::widget([
        'dataProvider' => $provider,
        'columns' => [
            /*'account_url:text:Аккаунт',*/
            [
                'label' => 'Аккаунт',
                'format' => 'raw',
                'value' => function($data){
                    return Html::a($data->vk_username, $data->account_url, ['target' =>'_blank']);
                },
            ],
            [
                'label' => 'Срок действия access token',
                'format' => 'text',
                'value' => function($data){

        if ($data->access_expires_in == 0) {
            return 'Бессрочный';
        } else {
            return date('Y-m-d', $data->access_expires_in);
        }
                },
            ],
            [
                'class' => ActionColumn::className(),
                'header'=>'Удалить аккаунт',
                'headerOptions' => ['width' => '80'],
                'template' => '{delete}',
                'buttons'  => [

                    'delete' => function($url, $data) {

                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', ['delete', 'id' => $data['id']], [

                            'title' => 'Удалить аккаунт ' . $data['vk_username'], 'data-confirm' => 'Все ваши группы для публикации также удалятся. Удалить этот аккаунт?','data-method' => 'post']);


                    }
                ],
            ],
        ],
    ]) ?>


    <!--<div class="access-token-modal"><?/*= $this->render('_modal'); */?></div>-->
</div>

views/accounts/_appWarning.php
<?php
/**
 * 24.09.2019
 * 0:16
 */

use yii\bootstrap\Modal;
use yii\helpers\Html;


?>

<div><h3>
        У вас еще не создано ни одного приложения.
    </h3>
    <p>Чтобы публиковать посты, вам нужно <?= Html::a('создать свое приложение', '/applications') ?>.</p>
    <div style="background-color: #eeeeee"><i>Я хочу <?= Html::a('продолжать парсить', '/source') ?> без возможности
            публиковать посты.</i></div>

    <div class="access-token-modal"><?= $this->render('_modal'); ?></div>

</div>

views/accounts/_modal.php
<?php
/**
 * 25.09.2019
 * 22:01
 *
 * @var $errorCodeFromUser string
 */
use yii\bootstrap\Modal;
use yii\helpers\Html;
use app\assets\AccountAsset;


AccountAsset::register($this);
?>

<div>

    <p>Связать аккаунт с приложением, чтобы постить:</p>

    <div class="">

        <?php
        Modal::begin([
            'header' => '<p>1. Нажмите "Получить код".
</p><p>2. Подтвердите доступ приложения.</p><p>3. Cкопируйте адресную строку из новой вкладки в поле ниже. Нажмите кнопку "Сохранить". Копируйте адрес целиком.</p>',
            'toggleButton' => [
                'label' => 'Привязать аккаунт Вконтакте',
                'tag' => 'button',
                'class' => 'btn',
            ],
            'size' => 'modal-lg',
        ]); ?>

        <?= Html::img('https://i.ibb.co/8z6Xzfx/vk-code-page.png', ['width' => 600]) ?>
        <?= Html::a('Получить код!', '/accounts/get-code', ['class' => 'btn btn-primary', 'target' => '_blank', 'style' => 'margin-left: 70px']); ?>

        <hr>

        <?= Html::beginForm("/accounts/parse-code")?>

        <?= Html::input('text', 'code-input', '', ['id' => 'code-input-id']) ?>

        <?= Html::submitButton('Сохранить код', ['class' => 'btn btn-primary', 'name' => 'contact-button', 'id' => 'saveCodeBtn']) ?>

        <?= Html::endForm()?>

    </div>

    <?php Modal::end(); ?>

    <? if($errorCodeFromUser == 'length') { ?>
        <p id = 'modal-message'>Введенный адрес слишком короткий.</p> <?
    } else if ($errorCodeFromUser == 'value') {?>
        <p id = 'modal-message'>Введите, пожалуйста, правильный адрес.</p>
     <? } ?>

</div>

views/accounts/index.php
<?php
/**
 * 23.09.2019
 * 21:39
 */

//does have any applications
//$userApplications

?>

<?php
use yii\bootstrap\Modal;
use yii\helpers\Html;

//var_dump($userAccounts, $userApplications);

if ($userApplications && $userAccounts) {
    echo $this->render('_accTable', [
            'provider' => $provider,
    ]);
} else if (!$userApplications) {
    echo $this->render('_appWarning');
} else if (!$userAccounts) {
    echo $this->render('_modal', [
        'errorCodeFromUser' => false,
    ]);
}