controllers/NewsController.php
<?php
/**
 * Created by PhpStorm.
 * User: Dmytry Nebolsin
 * Date: 03.09.2019
 * Time: 17:24
 */

namespace app\controllers;


use app\models\NewsAddForm;
use app\models\tables\News;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;

class NewsController extends Controller
{

    public function behaviors()
    {
        return [

            'access' => [
                'class' => AccessControl::className(),
                'only' => ['create', 'delete', 'save', 'update'],
                'rules' => [
                    [
                        'actions' => ['create'],
                        'allow' => true,
                        'roles' => ['NewsCreate'],
                    ],
                    [
                        'actions' => ['update', 'save'],
                        'allow' => true,
                        'roles' => ['NewsUpdate'],
                    ],
                    [
                        'actions' => ['delete'],
                        'allow' => true,
                        'roles' => ['NewsDelete'],
                    ],
                ],
                'denyCallback' => function(){
                    echo 'Доступ запрещен';
                    exit();
                },
            ],
        ];
    }


public function actionIndex(){
    $query = News::find();
    $dataProvider = new ActiveDataProvider([
        'query' => $query,
        'pagination' => [
            'pageSize' => 10,
        ],
    ]);
    return $this->render('index', [
        'dataProvider' => $dataProvider,
    ]);
}
    public function actionView($id){
        return $this->render('view', [
            'model' => News::findOne($id)
        ]);
    }
    public function actionUpdate($id){
        return $this->render('update', [
            'model' => News::findOne($id)
        ]);
    }

    public function actionSave($id){
        if ($model = News::findOne($id)) {
            $model->load(\Yii::$app->request->post());
            $model->save();
            \Yii::$app->session->setFlash('success', "Измения сохранены");
        }  else {
            \Yii::$app->session->setFlash('error', "Не удалось сохранить изменения");
        }
        $this->redirect(\Yii::$app->request->referrer);
    }

    public function actionCreate(){
        $model = new News();
        if ($model->load(\Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['news/view', 'id' => $model->id]);
        }
        return $this->render('create', [
            'model' => $model,
        ]);

    }
    public function actionDelete($id)
    {
        News::findOne($id)->delete();

        return $this->redirect(['index']);
    }
}

views/news/create.php
<?php
$this->title = 'Создание новости';
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\tables\Tasks */
/* @var $form yii\widgets\ActiveForm */


?>

<div class="news_one_main row" style="width: 50%">

    <?php $form = ActiveForm::begin(); ?>

    <div class="col-lg-12">
        <?= $form->field($model, 'header')->textInput(['maxlength' => 100 ]) ?>
    </div>
    <div class="col-lg-12 news_text_area" style="min-height: 200px">
        <?= $form->field($model, 'text')->textarea(['minheight' => 2000]) ?>
    </div>
    <div class="col-lg-12">
        <?= $form->field($model, 'author')->textInput() ?>
    </div>

    <div class="col-lg-12">
        <?= $form->field($model, 'date_create')
            ->textInput(['type' => 'date'])
        ?>
    </div>

</div>
    <?= Html::submitButton("Сохранить", ['class' => 'btn btn-success']); ?>
    <?php ActiveForm::end(); ?>

views/news/index.php
<?php
use \yii\helpers\Html;
$this->title = 'Новости';

?>

<div class="form-group">
        <?= Yii::$app->user->can('NewsCreate') ?
            Html::a('Добавить новость', ['news/create'], ['class' => 'btn btn-success']):'' ?>
    </div>
<?php
/** @var \yii\data\ActiveDataProvider $dataProvider */
echo \yii\widgets\ListView::widget([
    'dataProvider' => $dataProvider,
    'itemView' => function($model){
        return \app\widgets\NewsPreview::widget(['model' => $model]);
    },
    'summary' => false,
    'options' => [
        'class' => 'news-container'
    ],
])
?>

views/news/update.php
<?php
$this->title = 'Редактирование новости';
use \yii\widgets\ActiveForm;
use yii\helpers\Url;
use \yii\helpers\Html;

?>

<div class="news_one_main row" style="width: 50%">
    <?php $form = ActiveForm::begin(['action' => Url::to(['news/save', 'id' => $model->id])]); ?>
    <div class="col-lg-12">
        <?= $form->field($model, 'header')->textInput(['maxlength' => 100 ]) ?>
    </div>
    <div class="col-lg-12 news_text_area" style="min-height: 200px">
        <?= $form->field($model, 'text')->textarea(['minheight' => 2000]) ?>
    </div>
    <div class="col-lg-12">
        <?= $form->field($model, 'author')->textInput() ?>
    </div>

    <div class="col-lg-12">
        <?= $form->field($model, 'date_create')
            ->textInput(['type' => 'date'])
        ?>
    </div>
</div>
<?= Html::submitButton("Сохранить", ['class' => 'btn btn-success']); ?>
<? ActiveForm::end() ?>

views/news/view.php
<?php
use yii\helpers\Url;

/** @var $model \app\models\tables\News */
?>


<div class="col-lg-12 col-xs-12">

    <div class="news-preview-header"><a href="<?= Url::to(['news/view', 'id' => $model->id]) ?>"><h4><?= $model->header ?></h4></a></div>
    <div class="news-preview-content"><p><?= $model->text?></p></div>
    <div class="news-preview-date">Автор: <?= $model->author ?> / Опубликовано: <?= $model->date_create?>
        <a href="<?= Url::to(['news/update', 'id' => $model->id]) ?>"> Редактировать</a>
        <a href="<?= Url::to(['news/delete', 'id' => $model->id]) ?>"> Удалить</a>
    <hr>
</div>